services:
  slack-bot:
    build:
      context: .
      dockerfile: slack-bot/Dockerfile
    volumes:
      - ./slack-bot/src:/app/src:ro  # Mount source code as read-only
      - ./slack-bot/docker_entrypoint.py:/app/docker_entrypoint.py:ro
      - ./data:/app/data:rw  # Mount data directory for development
    env_file:
      - .env  # Use development environment variables
    command: uv run python docker_entrypoint.py  # Use our custom entrypoint
    depends_on:
      - movie-api
    
  movie-api:
    build:
      context: ./movie-club-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./movie-club-api:/app:rw  # Mount entire app for hot-reloading
      - ./data:/app/data:rw
    environment:
      - DEBUG=True
    command: uv run uvicorn main:app --reload --host 0.0.0.0 --port 8000  # Enable hot-reloading for development
    # Add healthcheck to verify the API is actually accepting connections
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
